// YOUR PRIVATE KEY
export const PRIVATE_KEY = "YOUR_PRIVATE_KEY";

// ETHEREUM
export const ETHERSCAN_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_ETHEREUM_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_ETHEREUM_GOERLI_API_KEY = "YOUR_API_KEY";

// ARBITRUM
export const ARBISCAN_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_ARBITRUM_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_ARBITRUM_GOERLI_API_KEY = "YOUR_API_KEY";

// OPTIMISM
export const OPTIMISM_ETHERSCAN_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_OPTIMISM_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_OPTIMISM_GOERLI_API_KEY = "YOUR_API_KEY";

// POLYGON
export const POLYGONSCAN_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_POLYGON_API_KEY = "YOUR_API_KEY";
export const ALCHEMY_POLYGON_MUMBAI_API_KEY = "YOUR_API_KEY";
